source("mycred.R")
footer <- paste0("Use C, F, A, S, B", " | Version ", Sys.time())
rmarkdown::render("slides.Rmd", rmarkdown::slidy_presentation(footer=footer))
message("committing...")
git2r::commit(message="dev", all=TRUE)
message("pushing...")
git2r::push(credentials=cred)
message("finished!")
